server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  sql:
    init:
      mode: never

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN}

  activation:
    token-expiration-ms: ${ACTIVATION_TOKEN_EXPIRATION_MS}
    frontend-base-url: ${FRONTEND_BASE_URL}
    activation-path: ${ACTIVATION_PATH}

  documents:
    storage-dir: ${DOCUMENTS_STORAGE_DIR:./storage/documents}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    persistAuthorization: true
