server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:portail_b2b}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:simo.2006}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  sql:
    init:
      mode: never

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

app:
  jwt:
    secret: ${JWT_SECRET:dGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3ItamF2YS1zcHJpbmctYm9vdC1qd3QtYXV0aGVudGljYXRpb24=}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  cors:
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  activation:
    token-expiration-ms: ${ACTIVATION_TOKEN_EXPIRATION_MS:604800000}
    frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
    activation-path: ${ACTIVATION_PATH:/activate}